// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://umdauoszbjrbakrozprz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVtZGF1b3N6YmpyYmFrcm96cHJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4OTEzMDQsImV4cCI6MjA2NDQ2NzMwNH0.f4Uisqzj3apwmsE9jJzsryXoU0uB1jOT0451mH2ZWDU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);